### ISSUE TITLE
Emoji Size

### ISSUE THREAD

**Issue by Orbyt** [pladaria/react-emojione#10]
Currently, I can render emoji's from the message text using the following code:

`<p>{emojify(message.text, {output: 'unicode'})}</p>`

Here, I simply pass the entire message into the `emojify()` function, and it renders emojis where found. What I would like to do is increase the size of the emojis in the message, without increasing the font size of the rest of the message.

How can this be done?

**Comment by pladaria** [comment]
Have a look at the README.md. In the "advanced" section is an example.
Reopen the ticket if you find any issue.
