### ISSUE TITLE
Support `:+1:`

### ISSUE THREAD

**Issue by mhils** [pladaria/react-emojione#11]
We very often use `:+1:` and `:-1:` on GitHub, but those won't get emojified by `react-emojione`. Currently, only `:thumbsup:` and `:thumbsdown:` translate to 👍 and 👎 . Any chance to get support for `:+1:`? 😃

**Comment by pladaria** [comment]
Ok, I'm working in the next version with support for emojione v3

**Comment by pladaria** [comment]
Supported in latest relase (v5)
