### ISSUE TITLE
Emoji text is displayed with "text-align: right"

### ISSUE THREAD

**Issue by msalsas** [pladaria/react-emojione#14]
I have something like this:

    <div className="text-with-emojis">
        <Emojify>{text}</Emojify>
    </div>

where `text-with-emojis` class has the `text-align: right` css rule.
Then the displayed emojis look like this:
![captura de pantalla de 2017-06-20 11-40-02](https://user-images.githubusercontent.com/4210017/27326926-3d8c6a1c-55ad-11e7-8877-4f4fc681887e.png)

If I remove the `text-align: right` the emojis are displayed right:
![captura de pantalla de 2017-06-20 11-42-25](https://user-images.githubusercontent.com/4210017/27327040-8ed4b280-55ad-11e7-8881-5f4e562a4854.png)

I've been playing with css rules but can't find the solition. Any ideas?

**Comment by msalsas** [comment]
I've found out that adding `text-align: left` (or `center`) to the last `span` element solves the problem (probably at `emojione-sprite.js`). Would you accept a PR?

**Comment by pladaria** [comment]
Sorry for the delay. Yes please, send a PR
