### ISSUE TITLE
It doesn't support some of the emojis like :skull_and_crossbones:

### ISSUE THREAD

**Issue by farhantahir** [pladaria/react-emojione#17]
I'm using emoji-mart for emoji pikcer and emojione for rendering emojis on chat page.

But emojione doesn't support some of the emojis, like I faced the problem with :skull_and_crossbones: 

Can someone please help regarding this? 

Thanks

**Comment by pladaria** [comment]
should be supported in latest releases

**Comment by farhantahir** [comment]
Thanks
