### ISSUE TITLE
Not working on IE 11

### ISSUE THREAD

**Issue by jasonogasian** [pladaria/react-emojione#19]
I noticed that this package is making use of the Map class from ES2015 which isn't supported (fully?) before IE edge. The code specifically breaks down when trying to call the entries() function on the asciiRegExpToUnicode object.

Not sure if it's in your scope to fix it, but thought I'd mention it because it caused me quite a bit of hassle.

Cheers,

Jason

**Comment by pladaria** [comment]
Sorry you need to support IE11. Consider adding a polyfill for Map.
