### ISSUE TITLE
slowly

### ISSUE THREAD

**Issue by shiran1992** [pladaria/react-emojione#20]
Very high, emoji can be displayed, but the emoji is slow, I have an emoji list (about 50), and it took eight seconds to refresh.

**Comment by pladaria** [comment]
There must be something wrong in your code. We use this library to display an emoji selector where hundreds of emojis are rendered and it takes few milliseconds to render.

Can you please provide a code example to reproduce your problem (feel free to use something like https://codesandbox.io/s/new show your problem)
