### ISSUE TITLE
Support for raw html output?

### ISSUE THREAD

**Issue by artemjackson** [pladaria/react-emojione#23]
First, thank you for the nice lib!

Second, I'd like to use the lib with `contenteditable` block.
Contenteditable is a little bit tricky in React and, in short, it requires `dangerouslySetInnerHTML` to work.

So is it possible to add support for raw html output?

**Comment by pladaria** [comment]
Does this fits your needs?
```javascript
import ReactDOMServer from 'react-dom/server';

...
const html = ReactDOMServer.renderToStaticMarkup(element);
```

Alternatively there are several libraries to generate html from react elements, for example [this one](https://github.com/glenjamin/react-element-to-string)

**Comment by artemjackson** [comment]
@pladaria Thanks for a hint!

Actually I ended up with [draft-js](https://draftjs.org/) to work with content editable and rich text formatting
