### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by vonubisch** [pladaria/react-emojione#24]
When using the `emojify` function every emoji gets turned into `[object Object]`

React 16

**Comment by pladaria** [comment]
Can you please post a minimal source code where your issue gets reproduced?

Anyway, if you look at the first test:
```javascript
test('shortnames', t => {
    t.test('shortname alternates', t => {
        const result = emojify(':+1: :thumbsup:', { output: 'unicode' });
        const expected = '👍 👍';
        t.equals(result, expected, result);
        t.end();
    });
});
```
emojify seems to work
