### ISSUE TITLE
Internet Explorer crashes when using

### ISSUE THREAD

**Issue by ghost** [pladaria/react-emojione#28]
Hello there,
I find your tool extremely useful and have built it into my React application. However, I now have the problem that all browsers (Firefox 62, Firefox Developer 63, Opera 55, Chrome 69 tested) support react-emojione, but the Internet Explorer, the little piece of shit that throws a stacktrace. Which looks like this:

source code looks so:
```
...
import Emojify from 'react-emojione';
...
<Emojify style={{height: 20, width: 20}}>

<LanguageButton onClick={() => this.props.changeLanguageFunc("de")}>:flag_de:</LanguageButton>

<LanguageButton onClick={() => this.props.changeLanguageFunc("en")}>:flag_gb:</LanguageButton>

</Emojify>
...
```

**Comment by pladaria** [comment]
We are using this library in production with IE11 support. Which version are you targeting?
