### ISSUE TITLE
Newer Emoji's aren't being emojified

### ISSUE THREAD

**Issue by teckore** [pladaria/react-emojione#4]
There are new emoji's that are not being emojified, is there a way to fix this?

**Comment by pladaria** [comment]
Yes, the library uses an outdated set of emojis. It should be easy to update to use latest emojione set.
Hopefully I get some spare time soon for this task.

**Comment by ksaitor** [comment]
All we need is :unicorn:

**Comment by gibrit** [comment]
check my pull request ... it is supporting all emojis ..   like :avocado:   
upgrade to latest emojione package ..
 run
npm  run create-styles   
and
npm run create-emoji-data   
when new emojis 
commands

**Comment by pladaria** [comment]
v.3.0.0 released with latest emojione, please open an issue if you find any problems.
