### ISSUE TITLE
Error in basic usage, Not found error

### ISSUE THREAD

**Issue by Orbyt** [pladaria/react-emojione#5]
Basic setup, emojis dont appear and `net::ERR_FILE_NOT_FOUND` for path `MyProject/emojione.sprites.png` is printed to the console. `emojione.sprites.png` is a file located in the package, so I assume this is incorrect.

I can however get it working passing in `{output: 'unicode'}`. What might the issue be?

**Comment by PolGuixe** [comment]
Same here...

**Comment by pladaria** [comment]
Please, provide a code snippet.

You need to provide the path to the sprite (via options), which should be served by you or a CDN.

By using {output: 'unicode'} you are rendering your OS emojis (I guess you are using a mac), not emojione.
