### ISSUE TITLE
Need to be able to not put any styling at all

### ISSUE THREAD

**Issue by innocentamadi** [pladaria/react-emojione#6]
The default css styling for emojis  are a large array of rules that might not be required at all. I for one don't need any styling. Just the emoji.

I should be able to opt out of having my emoji specially styled by the default rules.

I could help with this if it's accepted as a useful enhancement.

**Comment by pladaria** [comment]
The rules are required to render the background. Otherwise you are simply outputting an Unicode character which your OS translates into an emoji. But this won't work in linux or windows.
