### ISSUE TITLE
Blank emojis

### ISSUE THREAD

**Issue by PolGuixe** [pladaria/react-emojione#8]
My emojis doesn't seem to load. 

Is this a wrapper of https://www.npmjs.com/package/emojione?

**Comment by sithembiso** [comment]
@PolGuixe any luck getting this working? I'm stuck as well.

**Comment by PolGuixe** [comment]
@sithembiso try using the outline option and restart your app.
;)

**Comment by sithembiso** [comment]
@PolGuixe I've been looking, but I can't find the `outline` option? Do you have a snippet for me of perhaps an exact place to look.

**Comment by PolGuixe** [comment]
@sithembiso I am very sorry, I wanted to mean `output` option.  See below. 

```emojify(':see_no_evil:', {output: 'unicode'})```

**Comment by pladaria** [comment]
Can you please post a fragment of your code?

btw, this is not a wrapper.

**Comment by PolGuixe** [comment]
This way it works: 
```
      <p>
       {emojify(':wrench:',{output:'unicode'})}with{emojify(':heart_eyes:',{output:'unicode'})} in the {emojify(':earth_africa:',{output:'unicode'})}
     </p>
```
without `{output:'unicode'}` it doesn't.
